INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fix door hinge", "maintenance", 94, "11/21/19", "11/29/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fix door hinge", "maintenance", 94, "11/21/19", "11/29/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fix door hinge", "maintenance", 94, "11/21/19", "11/29/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fix door hinge", "maintenance", 94, "11/21/19", "11/29/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fix door hinge", "maintenance", 94, "11/21/19", "11/29/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fix door hinge", "maintenance", 94, "11/21/19", "11/29/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fix door hinge", "maintenance", 94, "11/21/19", "11/29/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fix door hinge", "maintenance", 94, "11/21/19", "11/29/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fix door hinge", "maintenance", 94, "11/21/19", "11/29/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fix door hinge", "maintenance", 94, "11/21/19", "11/29/19");

INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);
INSERT INTO users (name, age) VALUES ("Blake", 35);

INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (13, 1, 1);


